services:
  middle:
    build:
      context: .
      dockerfile: ./docker/middle/Dockerfile
    container_name: middle
    volumes:
      - type: bind
        source: ./middle # ローカルのパス
        target: /workspace # コンテナ内のパス
      - type: volume
        source: node_modules # 名前付きボリューム
        target: /workspace/node_modules # コンテナ内のパス
    ports:
      - "5173:5173"

# https://zenn.dev/usma11dia0/articles/dockerfile_run_npm_not_working
volumes:
  node_modules:
