services:

  otp:
    image: opentripplanner/opentripplanner:2.5.0 # 2.6.0以降はTravel Time Analysis機能が削除されているため、2.5.0を指定
    container_name: opentripplanner
    environment:
      - JAVA_OPTS=-Xmx3G # メモリの最大ヒープ・サイズ（6G）
    volumes:
      - type: bind
        source: ./otp # ローカルのパス
        target: /var/opentripplanner # コンテナ内のパス
    command: [ '--load', '--serve' ]
    ports:
      - "8080:8080"
    restart: always

  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    container_name: app
    volumes:
      - type: bind
        source: ./app # ローカルのパス
        target: /workspace # コンテナ内のパス
      - type: volume
        source: node_modules_app # 名前付きボリューム
        target: /workspace/node_modules # コンテナ内のパス
    ports:
      - "8000:8000"
    restart: always

  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    container_name: web
    volumes:
      - type: bind
        source: ./web # ローカルのパス
        target: /workspace # コンテナ内のパス
      - type: volume
        source: node_modules_web # 名前付きボリューム
        target: /workspace/node_modules # コンテナ内のパス
    ports:
      - "5173:5173"
    restart: always

# https://zenn.dev/usma11dia0/articles/dockerfile_run_npm_not_working
volumes:
  node_modules_app:
  node_modules_web:
